In [5]:
import numpy as np
x=np.arange(90).reshape(30,-1)

In [11]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [17]:
def fun(y_sim, y_obs, y_err):
    return np.sum(np.divide((y_obs - y_sim)**2, y_err**2, where=y_err!= 0))

y_obs=np.array([3,4,5])
y_err=np.sqrt(y_obs)
np.apply_along_axis(fun,1,x, y_obs,y_err)

array([   7.05,    0.  ,    7.05,   28.2 ,   63.45,  112.8 ,  176.25,
        253.8 ,  345.45,  451.2 ,  571.05,  705.  ,  853.05, 1015.2 ,
       1191.45, 1381.8 , 1586.25, 1804.8 , 2037.45, 2284.2 , 2545.05,
       2820.  , 3109.05, 3412.2 , 3729.45, 4060.8 , 4406.25, 4765.8 ,
       5139.45, 5527.2 ])

In [19]:
 np.sum(np.divide((y_obs - x)**2, y_err**2, where=y_err!= 0), axis=1)

array([   7.05,    0.  ,    7.05,   28.2 ,   63.45,  112.8 ,  176.25,
        253.8 ,  345.45,  451.2 ,  571.05,  705.  ,  853.05, 1015.2 ,
       1191.45, 1381.8 , 1586.25, 1804.8 , 2037.45, 2284.2 , 2545.05,
       2820.  , 3109.05, 3412.2 , 3729.45, 4060.8 , 4406.25, 4765.8 ,
       5139.45, 5527.2 ])